from __future__ import annotations

import argparse
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Sequence

from .cache import CacheClearError, clear_cache
from .config import load_config
from .concordance import ConcordanceError, write_concordance
from .dry_run import dry_run_count_vocabula
from .ngram import NgramError, write_ngrams_from_config, write_ngrams_from_trace
from .nlp_hooks import (
    build_pipeline,
    build_sentence_splitter,
    count_group,
    render_stanza_package_table,
)
from .runner import run

try:
    from nlpo_toolkit.latin.cleaners import run_clean_corpus as clean_mod
except Exception:
    clean_mod = SimpleNamespace(main=lambda argv: 0)


def run_count_vocabula(
    *,
    project_root: Path,
    config_path: Path,
    group_by_file: bool = False,
) -> int:
    return run(
        project_root=project_root,
        config_path=config_path,
        group_by_file=group_by_file,
        load_config_fn=load_config,
        clean_mod=clean_mod,
        build_pipeline_fn=build_pipeline,
        build_sentence_splitter_fn=build_sentence_splitter,
        count_group_fn=count_group,
        render_stanza_package_table_fn=render_stanza_package_table,
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="nlpo")
    subparsers = parser.add_subparsers(dest="command", required=True)

    for name in ("count-vocabula", "count"):
        count_parser = subparsers.add_parser(name)
        count_parser.add_argument(
            "--project-root",
            type=Path,
            default=Path.cwd(),
            help="Project root used to resolve relative paths in the config.",
        )
        count_parser.add_argument(
            "--config",
            type=Path,
            default=None,
            help="YAML config path. Defaults to <project-root>/config/groups.config.yml.",
        )
        count_parser.add_argument(
            "--group-by-file",
            action="store_true",
            help="Write one frequency CSV per input file instead of one CSV per configured group.",
        )
        count_parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Validate config, paths, and matched files without running NLP.",
        )

    cache_parser = subparsers.add_parser("cache")
    cache_subparsers = cache_parser.add_subparsers(dest="cache_command", required=True)
    cache_clear_parser = cache_subparsers.add_parser("clear")
    cache_clear_parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
        help="Project root used to resolve the configured cache directory.",
    )
    cache_clear_parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="YAML config path. Defaults to <project-root>/config/groups.config.yml when it exists.",
    )

    concordance_parser = subparsers.add_parser("concordance")
    concordance_parser.add_argument(
        "--trace",
        type=Path,
        required=True,
        help="Trace TSV path generated by count-vocabula.",
    )
    concordance_parser.add_argument(
        "--keys",
        nargs="+",
        required=True,
        help="Search keys. Multiple values are accepted.",
    )
    concordance_parser.add_argument(
        "--window",
        type=int,
        default=5,
        help="Number of words to show on each side of the matched token.",
    )
    concordance_parser.add_argument(
        "--field",
        choices=("token", "lemma"),
        default="lemma",
        help="Trace field to search.",
    )
    concordance_parser.add_argument(
        "--format",
        choices=("tsv", "csv"),
        default="tsv",
        help="Output format.",
    )
    concordance_parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output file path. Defaults to standard output.",
    )

    ngram_parser = subparsers.add_parser("ngram")
    ngram_parser.add_argument(
        "--n",
        type=int,
        default=2,
        help="N-gram size.",
    )
    ngram_parser.add_argument(
        "--trace",
        type=Path,
        default=None,
        help="Trace TSV path generated by count-vocabula.",
    )
    ngram_parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
        help="Project root used with --config input.",
    )
    ngram_parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="YAML config path for groups input. Defaults to <project-root>/config/groups.config.yml.",
    )
    ngram_parser.add_argument(
        "--field",
        choices=("token", "lemma"),
        default="lemma",
        help="Trace field to use for n-grams.",
    )
    ngram_parser.add_argument(
        "--by-group",
        action="store_true",
        help="Aggregate n-grams separately for each trace group.",
    )
    ngram_parser.add_argument(
        "--min-count",
        type=int,
        default=1,
        help="Minimum frequency to include.",
    )
    ngram_parser.add_argument(
        "--top",
        type=int,
        default=None,
        help="Limit output to the top N n-grams.",
    )
    ngram_parser.add_argument(
        "--format",
        choices=("tsv", "csv"),
        default="tsv",
        help="Output format.",
    )
    ngram_parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output file path. Defaults to standard output.",
    )

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command in {"count-vocabula", "count"}:
        project_root = args.project_root.resolve()
        config_path = args.config
        if config_path is None:
            config_path = project_root / "config" / "groups.config.yml"
        elif not config_path.is_absolute():
            config_path = (project_root / config_path).resolve()

        if args.dry_run:
            return dry_run_count_vocabula(
                project_root=project_root,
                config_path=config_path,
                group_by_file=bool(args.group_by_file),
            )
        return run_count_vocabula(
            project_root=project_root,
            config_path=config_path,
            group_by_file=bool(args.group_by_file),
        )

    if args.command == "cache" and args.cache_command == "clear":
        project_root = args.project_root.resolve()
        config_path = args.config
        if config_path is not None and not config_path.is_absolute():
            config_path = (project_root / config_path).resolve()
        try:
            return clear_cache(project_root=project_root, config_path=config_path)
        except CacheClearError as exc:
            print(f"[ERROR] {exc}", file=sys.stderr)
            return 1

    if args.command == "concordance":
        try:
            return write_concordance(
                trace_path=args.trace,
                keys=list(args.keys),
                field=args.field,
                window=args.window,
                output_format=args.format,
                out_path=args.out,
            )
        except ConcordanceError as exc:
            print(f"[ERROR] {exc}", file=sys.stderr)
            return 1

    if args.command == "ngram":
        try:
            if args.trace is not None:
                return write_ngrams_from_trace(
                    trace_path=args.trace,
                    n=args.n,
                    field=args.field,
                    by_group=bool(args.by_group),
                    min_count=args.min_count,
                    top=args.top,
                    output_format=args.format,
                    out_path=args.out,
                )

            project_root = args.project_root.resolve()
            config_path = args.config
            if config_path is None:
                config_path = project_root / "config" / "groups.config.yml"
            elif not config_path.is_absolute():
                config_path = (project_root / config_path).resolve()

            return write_ngrams_from_config(
                project_root=project_root,
                config_path=config_path,
                n=args.n,
                field=args.field,
                by_group=bool(args.by_group),
                min_count=args.min_count,
                top=args.top,
                output_format=args.format,
                out_path=args.out,
            )
        except NgramError as exc:
            print(f"[ERROR] {exc}", file=sys.stderr)
            return 1

    parser.error(f"unknown command: {args.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
