from __future__ import annotations

from .support.rules import DependencyRule, DynamicImportAllowance
from .support.module_roles import ModuleRole, ModuleRolePolicy


CA = "nlpo_toolkit.corpus_analysis"
CLI = f"{CA}.cli"
STANDALONE_CLI_MODULES = (
    "nlpo_toolkit.latin.cleaners.run_clean_corpus",
    "nlpo_toolkit.latin.latin_wordlist.build_latin_wordlist",
)
COMPOSITION = f"{CA}.composition"
PORTS = f"{CA}.ports"

# Primary roles are exhaustive and exclusive. Every production module is selected
# below via a narrow exact selector or a genuinely homogeneous leaf package.
MODULE_ROLE_POLICIES: tuple[ModuleRolePolicy, ...] = (
    ModuleRolePolicy(
        ModuleRole.SHARED,
        exact_modules=(
            "nlpo_toolkit",
            "nlpo_toolkit.cleaner_contracts",
            "nlpo_toolkit.config_model",
            "nlpo_toolkit.immutable_collections",
            "nlpo_toolkit.configuration",
            "nlpo_toolkit.corpus_analysis",
            "nlpo_toolkit.corpus_analysis.archive.contracts",
            "nlpo_toolkit.corpus_analysis.artifacts",
            "nlpo_toolkit.corpus_analysis.artifacts.models",
            "nlpo_toolkit.corpus_analysis.config",
            "nlpo_toolkit.corpus_analysis.config.models",
            "nlpo_toolkit.corpus_analysis.corpus_errors",
            "nlpo_toolkit.corpus_analysis.features.errors",
            "nlpo_toolkit.corpus_analysis.planning",
            "nlpo_toolkit.corpus_analysis.ports",
            "nlpo_toolkit.corpus_analysis.publication_models",
            "nlpo_toolkit.corpus_analysis.publication_ports",
            "nlpo_toolkit.corpus_analysis.requests",
            "nlpo_toolkit.corpus_analysis.session_models",
            "nlpo_toolkit.corpus_analysis.token_artifact",
            "nlpo_toolkit.corpus_analysis.token_artifact.errors",
            "nlpo_toolkit.nlp",
            "nlpo_toolkit.nlp.contracts",
        ),
        recursive_packages=("nlpo_toolkit.serialization",),
    ),
    ModuleRolePolicy(
        ModuleRole.DOMAIN,
        exact_modules=(
            "nlpo_toolkit.comparison",
            "nlpo_toolkit.comparison.config",
            "nlpo_toolkit.comparison.engine",
            "nlpo_toolkit.comparison.errors",
            "nlpo_toolkit.comparison.metrics",
            "nlpo_toolkit.comparison.models",
            "nlpo_toolkit.comparison.results",
            "nlpo_toolkit.corpus_analysis.analysis_policy",
            "nlpo_toolkit.corpus_analysis.analysis_records",
            "nlpo_toolkit.corpus_analysis.analysis_results",
            "nlpo_toolkit.corpus_analysis.features",
            "nlpo_toolkit.corpus_analysis.features.engine",
            "nlpo_toolkit.corpus_analysis.features.filtering",
            "nlpo_toolkit.corpus_analysis.features.lexical",
            "nlpo_toolkit.corpus_analysis.features.mfw",
            "nlpo_toolkit.corpus_analysis.features.models",
            "nlpo_toolkit.corpus_analysis.features.upos",
            "nlpo_toolkit.corpus_analysis.normalizer",
            "nlpo_toolkit.corpus_analysis.partition_models",
            "nlpo_toolkit.corpus_analysis.partition_validation",
            "nlpo_toolkit.corpus_analysis.postprocessing",
            "nlpo_toolkit.corpus_analysis.postprocessing.dictionary",
            "nlpo_toolkit.corpus_analysis.postprocessing.lemma_normalization",
            "nlpo_toolkit.corpus_analysis.planning.validate",
            "nlpo_toolkit.corpus_analysis.planning.models",
            "nlpo_toolkit.corpus_analysis.ref_tags",
            "nlpo_toolkit.corpus_analysis.reporting",
            "nlpo_toolkit.corpus_analysis.reporting.models",
            "nlpo_toolkit.corpus_analysis.reporting.summary",
            "nlpo_toolkit.corpus_analysis.token_artifact.codec",
            "nlpo_toolkit.corpus_analysis.token_artifact.integrity",
            "nlpo_toolkit.corpus_analysis.token_artifact.schema",
            "nlpo_toolkit.latin.cleaners",
            "nlpo_toolkit.latin.cleaners.errors",
            "nlpo_toolkit.latin.cleaners.events",
            "nlpo_toolkit.latin.cleaners.models",
            "nlpo_toolkit.latin.cleaners.normalization",
            "nlpo_toolkit.latin.cleaners.rule_engine",
            "nlpo_toolkit.nlp.chunking",
            "nlpo_toolkit.nlp.roman_numerals",
            "nlpo_toolkit.nlp.vocabulary",
        ),
        recursive_packages=(
            "nlpo_toolkit.corpus_analysis.token_sequences",
            "nlpo_toolkit.latin.cleaners.corpora",
        ),
    ),
    ModuleRolePolicy(
        ModuleRole.APPLICATION,
        exact_modules=(
            "nlpo_toolkit.corpus_analysis.analysis_execution",
            "nlpo_toolkit.corpus_analysis.analysis_orchestration",
            "nlpo_toolkit.corpus_analysis.comparison_run_results",
            "nlpo_toolkit.corpus_analysis.concordance",
            "nlpo_toolkit.corpus_analysis.count_context",
            "nlpo_toolkit.corpus_analysis.count_command",
            "nlpo_toolkit.corpus_analysis.count_result",
            "nlpo_toolkit.corpus_analysis.count_result_builder",
            "nlpo_toolkit.corpus_analysis.dry_run",
            "nlpo_toolkit.corpus_analysis.execution_session",
            "nlpo_toolkit.corpus_analysis.features.service",
            "nlpo_toolkit.corpus_analysis.ngram",
            "nlpo_toolkit.corpus_analysis.planning.build",
            "nlpo_toolkit.corpus_analysis.planning.resolve",
            "nlpo_toolkit.corpus_analysis.post_analysis",
            "nlpo_toolkit.corpus_analysis.preprocessing",
            "nlpo_toolkit.corpus_analysis.postprocessing.service",
            "nlpo_toolkit.corpus_analysis.reporting.service",
            "nlpo_toolkit.corpus_analysis.partition_run_results",
            "nlpo_toolkit.corpus_analysis.runner",
            "nlpo_toolkit.corpus_analysis.runtime",
            "nlpo_toolkit.latin.cleaners.pipeline",
            "nlpo_toolkit.latin.cleaners.service",
        ),
        recursive_packages=("nlpo_toolkit.comparison.services",),
    ),
    ModuleRolePolicy(
        ModuleRole.INFRASTRUCTURE,
        exact_modules=(
            "nlpo_toolkit.comparison.frequency_io",
            "nlpo_toolkit.configuration.yaml_loader",
            "nlpo_toolkit.corpus_analysis.artifacts.planning",
            "nlpo_toolkit.corpus_analysis.artifacts.publication",
            "nlpo_toolkit.corpus_analysis.artifacts.publication_adapters",
            "nlpo_toolkit.corpus_analysis.cache",
            "nlpo_toolkit.corpus_analysis.cache_storage",
            "nlpo_toolkit.corpus_analysis.config.parser",
            "nlpo_toolkit.corpus_analysis.config.serializer",
            "nlpo_toolkit.corpus_analysis.config_references",
            "nlpo_toolkit.corpus_analysis.corpus",
            "nlpo_toolkit.corpus_analysis.diagnostic_trace",
            "nlpo_toolkit.corpus_analysis.io_utils",
            "nlpo_toolkit.corpus_analysis.postprocessing.lemma_normalization_io",
            "nlpo_toolkit.corpus_analysis.reporting.environment",
            "nlpo_toolkit.corpus_analysis.reporting.metadata",
            "nlpo_toolkit.corpus_analysis.reporting.publication_adapter",
            "nlpo_toolkit.corpus_analysis.token_artifact.paths",
            "nlpo_toolkit.corpus_analysis.token_artifact.reader",
            "nlpo_toolkit.corpus_analysis.token_artifact.validation",
            "nlpo_toolkit.corpus_analysis.token_artifact.writer",
            "nlpo_toolkit.latin.cleaners.config_loader",
            "nlpo_toolkit.latin.cleaners.lexicon",
            "nlpo_toolkit.latin.cleaners.registry",
            "nlpo_toolkit.latin.cleaners.rule_loader",
            "nlpo_toolkit.corpus_analysis.archive",
            "nlpo_toolkit.corpus_analysis.archive.copying",
            "nlpo_toolkit.corpus_analysis.archive.errors",
            "nlpo_toolkit.corpus_analysis.archive.file_metadata",
            "nlpo_toolkit.corpus_analysis.archive.git_metadata",
            "nlpo_toolkit.corpus_analysis.archive.inventory",
            "nlpo_toolkit.corpus_analysis.archive.manifest",
            "nlpo_toolkit.corpus_analysis.archive.models",
            "nlpo_toolkit.corpus_analysis.archive.service",
        ),
        recursive_packages=(
            "nlpo_toolkit.backends",
            "nlpo_toolkit.corpus_analysis.analysis_cache",
            "nlpo_toolkit.corpus_analysis.artifacts.writers",
        ),
    ),
    ModuleRolePolicy(
        ModuleRole.BOUNDARY,
        exact_modules=(
            "nlpo_toolkit.corpus_analysis.composition",
            "nlpo_toolkit.latin.cleaners.run_clean_corpus",
            "nlpo_toolkit.latin.latin_wordlist.build_latin_wordlist",
        ),
        recursive_packages=("nlpo_toolkit.corpus_analysis.cli",),
    ),
)

APPLICATION_MODULES = (
    f"{CA}.analysis_execution",
    f"{CA}.analysis_orchestration",
    f"{CA}.count_command",
    f"{CA}.dry_run",
    f"{CA}.execution_session",
    f"{CA}.features.service",
    f"{CA}.ngram",
    f"{CA}.concordance",
    f"{CA}.planning.build",
    f"{CA}.planning.resolve",
    f"{CA}.preprocessing",
    f"{CA}.post_analysis",
    f"{CA}.reporting.service",
    f"{CA}.runner",
    "nlpo_toolkit.comparison.services",
    "nlpo_toolkit.latin.cleaners.service",
)

PURE_MODULES = (
    "nlpo_toolkit.comparison.config",
    "nlpo_toolkit.comparison.engine",
    "nlpo_toolkit.comparison.metrics",
    "nlpo_toolkit.comparison.results",
    f"{CA}.analysis_results",
    f"{CA}.features.engine",
    f"{CA}.features.filtering",
    f"{CA}.features.lexical",
    f"{CA}.features.mfw",
    f"{CA}.features.models",
    f"{CA}.features.upos",
    f"{CA}.partition_models",
    f"{CA}.partition_validation",
    f"{CA}.planning.models",
    f"{CA}.planning.validate",
    f"{CA}.postprocessing.dictionary",
    f"{CA}.postprocessing.lemma_normalization",
    f"{CA}.reporting.models",
    f"{CA}.reporting.summary",
    f"{CA}.token_artifact.codec",
    f"{CA}.token_artifact.integrity",
    f"{CA}.token_artifact.schema",
    f"{CA}.token_sequences",
)

INFRASTRUCTURE_MODULES = (
    "nlpo_toolkit.backends",
    f"{CA}.analysis_cache",
    f"{CA}.archive.copying",
    f"{CA}.archive.file_metadata",
    f"{CA}.archive.git_metadata",
    f"{CA}.archive.inventory",
    f"{CA}.archive.manifest",
    f"{CA}.archive.models",
    f"{CA}.archive.service",
    f"{CA}.artifacts.publication",
    f"{CA}.artifacts.publication_adapters",
    f"{CA}.artifacts.writers",
    f"{CA}.cache_storage",
    f"{CA}.token_artifact.reader",
    f"{CA}.token_artifact.writer",
)

DEPENDENCY_RULES = (
    DependencyRule(
        "non-cli-no-cli",
        ("nlpo_toolkit",),
        (CLI,),
        excluded_source_prefixes=(CLI,),
        explanation="Production modules outside the CLI adapter must not depend on CLI modules.",
    ),
    DependencyRule(
        "standalone-cli-inward-only",
        ("nlpo_toolkit",),
        STANDALONE_CLI_MODULES,
        excluded_source_prefixes=STANDALONE_CLI_MODULES,
        explanation="Standalone CLI adapters may call application code, but production code must not depend on those adapters.",
    ),
    DependencyRule(
        "application-no-composition",
        APPLICATION_MODULES,
        (COMPOSITION,),
        explanation="Application services receive dependencies through ports; they do not assemble production implementations.",
    ),
    DependencyRule(
        "count-application-no-concrete-publication",
        (
            f"{CA}.analysis_orchestration",
            f"{CA}.analysis_execution",
            f"{CA}.post_analysis",
            f"{CA}.runner",
            f"{CA}.reporting.service",
        ),
        (
            f"{CA}.artifacts.writers",
            f"{CA}.artifacts.publication_adapters",
            f"{CA}.reporting.publication_adapter",
            f"{CA}.token_artifact.writer",
            f"{CA}.diagnostic_trace",
        ),
        explanation="Count application services depend on typed publication ports, not filesystem adapters or concrete writers.",
    ),
    DependencyRule(
        "composition-consumed-only-by-cli",
        ("nlpo_toolkit",),
        (COMPOSITION,),
        excluded_source_prefixes=(CLI, COMPOSITION),
        explanation="Only CLI bootstrap modules may consume the production composition root.",
    ),
    DependencyRule(
        "application-domain-no-backends",
        (CA,),
        ("nlpo_toolkit.backends",),
        excluded_source_prefixes=(CLI, COMPOSITION),
        explanation="Application and reporting code depend on NLP contracts, not concrete backend implementations.",
    ),
    DependencyRule(
        "ports-inward-only",
        (PORTS,),
        (CLI, COMPOSITION, "nlpo_toolkit.backends", "nlpo_toolkit.latin.cleaners", f"{CA}.archive", f"{CA}.artifacts.writers"),
        allowed_target_prefixes=(f"{CA}.archive.contracts",),
        explanation="Ports contain contracts and immutable dependency containers, never concrete adapters.",
    ),
    DependencyRule(
        "infrastructure-no-composition-or-cli",
        INFRASTRUCTURE_MODULES,
        (CLI, COMPOSITION),
        explanation="Infrastructure implements inward-facing contracts and must not know the bootstrap or CLI.",
    ),
    DependencyRule(
        "backend-domain-independent",
        ("nlpo_toolkit.backends",),
        (CA,),
        explanation="NLP backends implement NLP contracts and remain independent of corpus-analysis applications.",
    ),
    DependencyRule(
        "comparison-independent",
        ("nlpo_toolkit.comparison",),
        (CA,),
        explanation="The comparison package is reusable and independent of corpus-analysis orchestration.",
    ),
    DependencyRule(
        "comparison-config-inward",
        ("nlpo_toolkit.comparison.config",),
        ("nlpo_toolkit.comparison.engine", "nlpo_toolkit.comparison.results", "nlpo_toolkit.comparison.services"),
        explanation="Comparison configuration is a lower-level contract.",
    ),
    DependencyRule(
        "comparison-core-no-services",
        ("nlpo_toolkit.comparison.engine", "nlpo_toolkit.comparison.metrics"),
        ("nlpo_toolkit.comparison.config", "nlpo_toolkit.comparison.frequency_io", "nlpo_toolkit.comparison.services", CLI),
        explanation="Comparison calculations do not depend on configuration, adapters, or services.",
    ),
    DependencyRule(
        "comparison-results-no-services",
        ("nlpo_toolkit.comparison.results",),
        ("nlpo_toolkit.comparison.frequency_io", "nlpo_toolkit.comparison.services", CLI),
        explanation="Comparison results may own configured result values but do not depend on adapters or services.",
    ),
    DependencyRule(
        "planning-models-inward",
        (f"{CA}.planning.models",),
        (f"{CA}.planning.build", f"{CA}.planning.resolve", f"{CA}.planning.validate", f"{CA}.preprocessing"),
        explanation="Planning models are independent values shared by planning stages.",
    ),
    DependencyRule(
        "planning-validate-pure",
        (f"{CA}.planning.validate",),
        (f"{CA}.planning.build", f"{CA}.planning.resolve", f"{CA}.preprocessing", "nlpo_toolkit.configuration"),
        explanation="Validation checks plans without resolving files or executing preprocessing.",
    ),
    DependencyRule(
        "planning-build-no-later-stage",
        (f"{CA}.planning.build",),
        (f"{CA}.planning.resolve", f"{CA}.preprocessing"),
        explanation="Plan construction does not execute later resolution or preprocessing stages.",
    ),
    DependencyRule(
        "planning-resolve-no-build",
        (f"{CA}.planning.resolve",),
        (f"{CA}.planning.build", "nlpo_toolkit.configuration"),
        explanation="Resolution consumes a plan and never rebuilds or reloads its configuration.",
    ),
    DependencyRule(
        "token-artifact-core-inward",
        (f"{CA}.token_artifact.schema", f"{CA}.token_artifact.codec"),
        (f"{CA}.token_artifact.reader", f"{CA}.token_artifact.writer", f"{CA}.token_artifact.validation"),
        explanation="Token artifact schemas and codecs are independent of I/O adapters and validation workflows.",
    ),
    DependencyRule(
        "token-artifact-reader-writer-independent",
        (f"{CA}.token_artifact.reader",),
        (f"{CA}.token_artifact.writer",),
        explanation="Reading and publication are separate adapters.",
    ),
    DependencyRule(
        "token-artifact-writer-reader-independent",
        (f"{CA}.token_artifact.writer",),
        (f"{CA}.token_artifact.reader",),
        explanation="Reading and publication are separate adapters.",
    ),
    DependencyRule(
        "token-sequences-reusable",
        (f"{CA}.token_sequences",),
        (f"{CA}.ngram", f"{CA}.concordance", CLI, f"{CA}.token_artifact.reader", f"{CA}.corpus"),
        explanation="Token sequence consumers depend on the common sequence domain, never the reverse.",
    ),
    DependencyRule(
        "artifact-models-inward",
        (f"{CA}.artifacts.models", f"{CA}.artifacts.planning"),
        (f"{CA}.artifacts.writers", f"{CA}.artifacts.publication", f"{CA}.reporting"),
        explanation="Artifact inventory and planning are independent of publication and reporting.",
    ),
    DependencyRule(
        "analysis-result-inward",
        (f"{CA}.analysis_results",),
        (f"{CA}.artifacts.writers", f"{CA}.reporting"),
        explanation="Analysis results do not depend on their publication adapters.",
    ),
    DependencyRule(
        "reporting-models-inward",
        (f"{CA}.reporting.models", f"{CA}.reporting.metadata", f"{CA}.reporting.summary"),
        (f"{CA}.reporting.service", f"{CA}.artifacts.writers"),
        explanation="Reporting values, metadata construction, and rendering are independent of publication orchestration.",
    ),
)

# There are currently no justified dynamic-import exceptions. Entries must name a
# narrow source/target and explain why static composition cannot be used.
DYNAMIC_IMPORT_ALLOWANCES: tuple[DynamicImportAllowance, ...] = ()

SERIALIZATION_BOUNDARY_MODULES = (
    "nlpo_toolkit.serialization",
    "nlpo_toolkit.configuration.yaml_loader",
    f"{CA}.config.parser",
    f"{CA}.config.serializer",
    f"{CA}.analysis_cache.codec",
    f"{CA}.artifacts.writers",
    f"{CA}.reporting.metadata",
    f"{CA}.archive.manifest",
    f"{CA}.cli.compare_rendering",
    f"{CA}.cli.output",
    f"{CA}.diagnostic_trace",
    "nlpo_toolkit.latin.cleaners.config_loader",
    "nlpo_toolkit.latin.latin_wordlist.build_latin_wordlist",
)

PACKAGE_CYCLE_GROUPS = (
    "nlpo_toolkit.backends",
    "nlpo_toolkit.comparison",
    "nlpo_toolkit.configuration",
    "nlpo_toolkit.corpus_analysis.analysis_cache",
    "nlpo_toolkit.corpus_analysis.archive",
    "nlpo_toolkit.corpus_analysis.artifacts",
    "nlpo_toolkit.corpus_analysis.cli",
    "nlpo_toolkit.corpus_analysis.features",
    "nlpo_toolkit.corpus_analysis.planning",
    "nlpo_toolkit.corpus_analysis.postprocessing",
    "nlpo_toolkit.corpus_analysis.reporting",
    "nlpo_toolkit.corpus_analysis.token_artifact",
    "nlpo_toolkit.corpus_analysis.token_sequences",
    "nlpo_toolkit.latin.cleaners",
    "nlpo_toolkit.nlp",
    "nlpo_toolkit.serialization",
)
